[package]
name = "advent-2016"
version = "0.1.0"
authors = ["Peter Burns <rictic@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
